# Generated by Django 4.2.17 on 2024-12-31 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_user_groups_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
