# Generated by Django 4.2.17 on 2024-12-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_body',
            field=models.TextField(default='Your message here'),
        ),
    ]
