# Generated by Django 4.2.17 on 2024-12-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
