# Generated by Django 4.2.17 on 2024-12-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_conversation_created_at_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
